spring.application.name=devshowcase-api

# Configuração do Banco de Dados H2 (Em Memória)
spring.datasource.url=jdbc:h2:mem:devshowcasedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração do Swagger UI
springdoc.swagger-ui.path=/swagger-ui/index.html